export const estadosBrasileiros = [
    { value: '12', label: 'Acre' },               
    { value: '27', label: 'Alagoas' },            
    { value: '16', label: 'Amapá' },             
    { value: '13', label: 'Amazonas' },           
    { value: '29', label: 'Bahia' },              
    { value: '23', label: 'Ceará' },              
    { value: '53', label: 'Distrito Federal' },   
    { value: '32', label: 'Espírito Santo' },     
    { value: '52', label: 'Goiás' },            
    { value: '21', label: 'Maranhão' },           
    { value: '51', label: 'Mato Grosso' },        
    { value: '50', label: 'Mato Grosso do Sul' }, 
    { value: '31', label: 'Minas Gerais' },       
    { value: '15', label: 'Pará' },               
    { value: '25', label: 'Paraíba' },            
    { value: '41', label: 'Paraná' },             
    { value: '26', label: 'Pernambuco' },         
    { value: '22', label: 'Piauí' },              
    { value: '33', label: 'Rio de Janeiro' },     
    { value: '24', label: 'Rio Grande do Norte' },
    { value: '43', label: 'Rio Grande do Sul' }, 
    { value: '11', label: 'Rondônia' },           
    { value: '14', label: 'Roraima' },            
    { value: '42', label: 'Santa Catarina' },     
    { value: '35', label: 'São Paulo' },          
    { value: '28', label: 'Sergipe' },            
    { value: '17', label: 'Tocantins' }           
];

export const tiposEstabelecimentos = [
    { value: '1', label: 'Posto de Saúde' },
    { value: '2', label: 'Centro de Saúde/Unidade Básica' },
    { value: '4', label: 'Policlínica' },
    { value: '5', label: 'Hospital Geral' },
    { value: '7', label: 'Hospital Especializado' },
    { value: '15', label: 'Unidade Mista' },
    { value: '20', label: 'Pronto Socorro Geral' },
    { value: '21', label: 'Pronto Socorro Especializado' },
    { value: '22', label: 'Consultório Isolado' },
    { value: '32', label: 'Unidade Móvel Fluvial' },
    { value: '36', label: 'Clínica/Centro de Especialidade' },
    { value: '39', label: 'Unidade de Apoio Diagnóstico e Terapia (SADT Isolado)' },
    { value: '40', label: 'Unidade Móvel Terrestre' },
    { value: '42', label: 'Unidade Móvel de Nível Pré-Hospitalar na Área de Urgência' },
    { value: '43', label: 'Farmácia' },
    { value: '50', label: 'Unidade de Vigilância em Saúde' },
    { value: '60', label: 'Cooperativa ou Empresa de Cessão de Trabalhadores na Saúde' },
    { value: '61', label: 'Centro de Parto Normal - Isolado' },
    { value: '62', label: 'Hospital/Dia - Isolado' },
    { value: '64', label: 'Central de Regulação de Serviços de Saúde' },
    { value: '67', label: 'Laboratório Central de Saúde Pública (LACEN)' },
    { value: '68', label: 'Central de Gestão em Saúde' },
    { value: '69', label: 'Centro de Atenção Hemoterapia e/ou Hematológica' },
    { value: '70', label: 'Centro de Atenção Psicossocial' },
    { value: '71', label: 'Centro de Apoio à Saúde da Família' },
    { value: '72', label: 'Unidade de Atenção à Saúde Indígena' },
    { value: '73', label: 'Pronto Atendimento' },
    { value: '74', label: 'Polo Academia da Saúde' },
    { value: '75', label: 'Telemedicina' },
    { value: '76', label: 'Central de Regulação Médica das Urgências' },
    { value: '77', label: 'Serviço de Atenção Domiciliar Isolado (Home Care)' },
    { value: '78', label: 'Unidade de Atenção em Regime Residencial' },
    { value: '79', label: 'Oficina Ortopédica' },
    { value: '80', label: 'Laboratório de Saúde Pública' },
    { value: '81', label: 'Central de Regulação do Acesso' },
    { value: '82', label: 'Central de Notificação, Captação e Distribuição de Órgãos Estadual' },
    { value: '83', label: 'Polo de Prevenção de Doenças e Agravos e Promoção da Saúde' },
    { value: '84', label: 'Central de Abastecimento' },
    { value: '85', label: 'Centro de Imunização' }
  ];

   